### ISSUE TITLE
Publish official releases that include variant_definitions.py

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-hardware-definitions#1]
Several [other projects](https://github.com/NebraLtd/hm-diag/pull/92#discussion_r683079112) depend on `variant_definitions.py`. We currently use several different strategies for adding the dependency: wget from Dockerfile, copy into `lib/`, copy into some other directory. Instead, an official release should be pushed and included as a normal python dependency.

**Acceptance criteria**
- Tagged release on Github
- Release publicly available so that it can be added with `pip install`

**Comment by shawaj** [comment]
https://pypi.org/project/hm-hardware-defs/
