### ISSUE TITLE
Nebra Indoor Hotspot Gen GPIO 25 - LED Status Details Missing 

### ISSUE THREAD

**Issue by salmanfarisvp** [NebraLtd/helium-hardware-definitions#8]
Nebra Indoor Hotspot Gen 1 - GPIo 25 LED Status Details Missing, It would be great if we have the documentation.

**Comment by shawaj** [comment]
@salmanfarisvp what do you mean by this?

**Comment by salmanfarisvp** [comment]
I mean LED blinking pattern documentation.

**Comment by shawaj** [comment]
oh i see - on the status led you mean? the green one?

**Comment by salmanfarisvp** [comment]
Yes, The outside green led one.  I believe with the blink pattern we can find issues.

**Comment by shawaj** [comment]
@salmanfarisvp it is defined here:

https://github.com/NebraLtd/hm-config/blob/d043e7f16e1ad7f5787548801ec381374b2255fe/gatewayconfig/processors/led_processor.py#L17-L25

**Comment by shawaj** [comment]
Blink fast if diagnostics are not OK
Blink slow if advertising bluetooth
Solid if diagnostics are OK and not advertising

**Comment by salmanfarisvp** [comment]
Thanks, From the blinking pattern, is it able to know the exact issue? Like 10 blink patterns is for LoRa, 5 blinks for network..etc

**Comment by shawaj** [comment]
> Thanks, From the blinking pattern, is it able to know the exact issue? Like 10 blink patterns is for LoRa, 5 blinks for network..etc

@salmanfarisvp Not currently no. It just if there is any error.

The 4 blinks on the blue led on daughterboard is usually a network connection issue.

Perhaps open a feature request issue on hm-config to add different LED patterns for different issues
